Linear_regression
---

In [95]:
import pandas as pd
import numpy as np
from numpy import genfromtxt
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split

In [96]:
df = pd.read_csv('Student_Performance.csv')
column_names = df.columns.tolist()
df['Performance Index'] = df['Performance Index'].astype(int)
for ind in range(len(df['Extracurricular Activities'])):
    if df.loc[ind, 'Extracurricular Activities'] == "Yes": 
        df.loc[ind, 'Extracurricular Activities'] = 1
    else:
        df.loc[ind, 'Extracurricular Activities'] = 0
df.corr('pearson')       


Hours Studied  Previous Scores  \
Hours Studied                          1.000000        -0.012390   
Previous Scores                       -0.012390         1.000000   
Extracurricular Activities             0.003873         0.008369   
Sleep Hours                            0.001245         0.005944   
Sample Question Papers Practiced       0.017463         0.007888   
Performance Index                      0.373730         0.915189   

                                  Extracurricular Activities  Sleep Hours  \
Hours Studied                                       0.003873     0.001245   
Previous Scores                                     0.008369     0.005944   
Extracurricular Activities                          1.000000    -0.023284   
Sleep Hours                                        -0.023284     1.000000   
Sample Question Papers Practiced                    0.013103     0.003990   
Performance Index                                   0.024525     0.048106   

                                  Sample Question Papers Practiced  \
Hours Studied                                             0.017463   
Previous Scores                                           0.007888   
Extracurricular Activities                                0.013103   
Sleep Hours                                               0.003990   
Sample Question Papers Practiced                          1.000000   
Performance Index                                         0.043268   

                                  Performance Index  
Hours Studied                              0.373730  
Previous Scores                            0.915189  
Extracurricular Activities                 0.024525  
Sleep Hours                                0.048106  
Sample Question Papers Practiced           0.043268  
Performance Index                          1.000000

In [97]:
data = df.to_numpy(dtype='int')
data

array([[ 7, 99,  1,  9,  1, 91],
       [ 4, 82,  0,  4,  2, 65],
       [ 8, 51,  1,  7,  2, 45],
       ...,
       [ 6, 83,  1,  8,  5, 74],
       [ 9, 97,  1,  7,  0, 95],
       [ 7, 74,  0,  8,  1, 64]])

In [98]:
# Все столбцы, кроме последнего
X = data[:, :-1]

# Последний столбец
y = data[:, -1]

In [104]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
size = len(X_train[0])
print(len(X_train), len(y_train), len(X_test), len(y_test))

6700 6700 3300 3300


In [117]:
class Linear_regression:
    def __init__(self, report_count = 10):
        self.w = np.random.randn(size, 1)
        self.b = np.random.randint(11)*0.1
        self.report_count = report_count
    
    def z(self, X_train):
        print(self.w)
        print(X_train)
        print(np.dot(X_train, self.w))
        return np.dot(X_train, self.w)+self.b
    
    def MSE(self, y_pred, y_actual):
        sum = 0
        for i in range(len(y_actual)):
            sum += pow((y_actual[i]-y_pred[i]), 2)
        return sum/len(y_actual)

    def MAE(self, y_pred, y_actual):
        sum = 0
        for i in range(len(y_actual)):
            sum+=np.abs(y_actual-y_pred)
        return sum/len(y_actual)
    
    def train(self, X_train, y_train, X_test, y_test, epochs = 100, learning_rate = 0.05, loss_func = 'MSE'):
        if loss_func == 'MSE':
            for epoch in range(epochs):
                dw = np.zeros((1, size))
                db = 0
                for i in range(len(X_train)):
                    y_pred = self.z(X_train[i])
                    dw+=2 * X_train[i] * (y_pred[i] - y_train[i])
                    db+=2*(y_pred[i] - y_train[i])

                dw/=size
                db/=size

                self.w-=dw*learning_rate
                self.b-=db*learning_rate

                if(epoch%self.report_count == 0):
                    print('-------------------------')
                    print('Train Error: ', self.MSE(y_pred, y_train))
                    print('Test Error: ', self.MSE(self.z(X_test), y_test))
        else:
            print('NOT READY')
    
    def predict_pocket(self, X_test):
        predict = self.z(X_test)
        return predict
    
    def predict_object(self, obj):
        predict = np.dot(self.w, obj) + self.b
        return predict

In [118]:
lin = Linear_regression(10)
lin.train(X_train, y_train, X_test, y_test, 500, 0.05, 'MSE')

[[-0.21459479]
 [ 0.96294555]
 [-0.54396192]
 [-0.10347177]
 [-0.42799962]]
[ 3 81  1  8  5]
[73.84307111]
[[-0.21459479]
 [ 0.96294555]
 [-0.54396192]
 [-0.10347177]
 [-0.42799962]]
[ 1 88  1  8  4]
[81.44087916]


IndexError: index 1 is out of bounds for axis 0 with size 1